x=read.csv("D:/cuckoo/final year project/SAMPLE.csv")
z=x[,-c(1,1)]
m=apply(z,2,mean)
s=apply(z,2,sd)
z<-scale(z,m,s)
distance<-dist(z)
a=hclust(distance)
plot(a)
plot(a,labels=x$id, main='Default from hclust')
plot(a,hang=-1)
b<-hclust(distance,method="average")

plot(b,hang=-1)
membera=cutree(a,15)
table(membera)
memberb=cutree(b,15)
table(memberb)
aggregate(z,list(member),mean)
library(cluster)
plot(silhouette(cutree(a,15),distance))
